spring.application.name=kanban-saas

# Conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ad2345e2450de83017467a770b7074589fd3aa730e88a788b5e5d8ad8b49c0d424edb6709874b55aa4fad32985a343b17e5e5bb4c01aad3910130931d300116d